# Generated by Django 5.2.11 on 2026-02-18 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('muscle_groups', models.JSONField(blank=True, default=list, help_text='List of muscle groups, e.g. ["quads", "glutes"]')),
                ('equipment', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('demo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_demo_images', to='media_library.mediafile')),
                ('demo_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_demo_videos', to='media_library.mediafile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseInWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='12', help_text='e.g. "12", "8-12", "AMRAP", "30 sec"', max_length=50)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('superset_group', models.PositiveIntegerField(blank=True, help_text='Exercises with the same number are supersetted together.', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_entries', to='workouts.exercise')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_covers', to='media_library.mediafile')),
                ('exercises', models.ManyToManyField(related_name='workouts', through='workouts.ExerciseInWorkout', to='workouts.exercise')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exerciseinworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_entries', to='workouts.workout'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciseinworkout',
            unique_together={('workout', 'ordering')},
        ),
    ]
